import './style.css'
import link from './partials/link.hbs';

const app = document.querySelector('#app');
const { innerHTML } = app;
app.innerHTML = innerHTML + link({ href: "https://handlebarsjs.com/", slot: 'Docs (Generated by JavaScript)' });
